#!/usr/bin/env python3
"""
Upload files to Tencent COS in one of two modes:

  --manifest PATH           Upload files listed in upload-manifest.json
                            (generated by GenerateUploadManifestStep on the Unity side)

  --dir LOCAL_DIR --remote-prefix PREFIX
                            Walk a local directory and upload everything under it.
                            Use this for WebGL player output, raw artifact folders, etc.

Sets Content-Type and Content-Encoding metadata automatically based on file
extension so browsers can serve compressed WebGL builds directly from COS
(Brotli .br / Gzip .gz).

Required env vars: TENCENT_SECRET_ID, TENCENT_SECRET_KEY, COS_BUCKET, COS_REGION
Optional:          COS_CONCURRENCY (default 8)
"""
import argparse
import concurrent.futures
import json
import os
import sys
import threading

try:
    from qcloud_cos import CosConfig, CosS3Client
    from qcloud_cos.cos_exception import CosClientError, CosServiceError
except ImportError:
    sys.stderr.write(
        "ERROR: cos-python-sdk-v5 not installed. "
        "Run: pip install -r tools/requirements.txt\n"
    )
    sys.exit(2)


# Content-Type by file extension. Items not listed default to COS auto-detection.
CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".htm":  "text/html; charset=utf-8",
    ".js":   "application/javascript; charset=utf-8",
    ".mjs":  "application/javascript; charset=utf-8",
    ".css":  "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".wasm": "application/wasm",
    ".data": "application/octet-stream",
    ".symbols": "application/octet-stream",
    ".unityweb": "application/octet-stream",
    ".bundle":   "application/octet-stream",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif":  "image/gif",
    ".svg":  "image/svg+xml",
    ".ico":  "image/x-icon",
    ".txt":  "text/plain; charset=utf-8",
    ".xml":  "application/xml; charset=utf-8",
}


def detect_metadata(rel_path):
    """Return (Content-Type, Content-Encoding) tuple for upload metadata."""
    base = rel_path.lower()
    if base.endswith(".br"):
        return CONTENT_TYPES.get(os.path.splitext(base[:-3])[1]), "br"
    if base.endswith(".gz"):
        return CONTENT_TYPES.get(os.path.splitext(base[:-3])[1]), "gzip"
    return CONTENT_TYPES.get(os.path.splitext(base)[1]), None


def env(name, default=None):
    v = os.environ.get(name)
    return v if v is not None and v != "" else default


def build_manifest_from_dir(local_dir, remote_prefix):
    """Walk a directory and produce an in-memory manifest matching upload-manifest.json schema."""
    base = os.path.abspath(local_dir)
    if not os.path.isdir(base):
        raise FileNotFoundError(f"Local directory not found: {base}")
    files = []
    for root, _, filenames in os.walk(base):
        for fn in filenames:
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, base).replace(os.sep, "/")
            files.append({
                "relativePath": rel,
                "size": os.path.getsize(full),
                "sha256": "",
            })
    return {
        "schema": "t2fbuild.upload-manifest.v1",
        "provider": "directory-scan",
        "localDirectory": base,
        "remotePrefix": remote_prefix if remote_prefix.endswith("/") else remote_prefix + "/",
        "files": files,
    }


def load_manifest_file(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        sys.stderr.write(f"ERROR: failed to read manifest '{path}': {e}\n")
        sys.exit(2)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("manifest_pos", nargs="?", help=argparse.SUPPRESS)
    parser.add_argument("--manifest", dest="manifest_opt", help="Path to upload-manifest.json")
    parser.add_argument("--dir", help="Walk and upload a local directory")
    parser.add_argument("--remote-prefix", help="Remote prefix on COS (required with --dir)")
    parser.add_argument("--dry-run", action="store_true", help="Print operations without uploading")
    parser.add_argument(
        "--concurrency",
        type=int,
        default=int(env("COS_CONCURRENCY", "8")),
        help="Concurrent upload threads (default 8 / COS_CONCURRENCY)",
    )
    args = parser.parse_args()

    secret_id = env("TENCENT_SECRET_ID")
    secret_key = env("TENCENT_SECRET_KEY")
    bucket = env("COS_BUCKET")
    region = env("COS_REGION")

    missing = [
        n for n, v in [
            ("TENCENT_SECRET_ID", secret_id),
            ("TENCENT_SECRET_KEY", secret_key),
            ("COS_BUCKET", bucket),
            ("COS_REGION", region),
        ] if not v
    ]
    if missing:
        sys.stderr.write(f"ERROR: missing required env vars: {', '.join(missing)}\n")
        sys.exit(2)

    if args.dir:
        if not args.remote_prefix:
            sys.stderr.write("ERROR: --remote-prefix is required when using --dir\n")
            sys.exit(2)
        try:
            manifest = build_manifest_from_dir(args.dir, args.remote_prefix)
        except FileNotFoundError as e:
            sys.stderr.write(f"ERROR: {e}\n")
            sys.exit(2)
        source_desc = f"directory {args.dir}"
    else:
        manifest_path = args.manifest_opt or args.manifest_pos
        if not manifest_path:
            sys.stderr.write(
                "ERROR: specify either --manifest <path> or --dir <local> --remote-prefix <prefix>\n"
            )
            sys.exit(2)
        manifest = load_manifest_file(manifest_path)
        source_desc = f"manifest {manifest_path}"

    local_dir = manifest["localDirectory"]
    remote_prefix = manifest["remotePrefix"]
    files = manifest["files"]

    print(f"Source:      {source_desc}")
    print(f"Provider:    {manifest.get('provider', 'unknown')}")
    print(f"Target:      {manifest.get('target', 'unknown')}")
    print(f"Version:     {manifest.get('buildVersion', '-')}")
    print(f"Local:       {local_dir}")
    print(f"Remote:      cos://{bucket}/{remote_prefix} ({region})")
    print(f"Files:       {len(files)}")
    print(f"Concurrency: {args.concurrency}")
    if args.dry_run:
        print("Mode:        DRY-RUN")
    print()

    client = CosS3Client(CosConfig(Region=region, SecretId=secret_id, SecretKey=secret_key))

    state = {"done": 0, "bytes": 0}
    state_lock = threading.Lock()
    errors = []
    errors_lock = threading.Lock()
    total = len(files)

    def upload_one(entry):
        rel = entry["relativePath"]
        local_path = os.path.join(local_dir, rel)
        remote_key = remote_prefix + rel
        content_type, content_encoding = detect_metadata(rel)

        kwargs = {}
        if content_type:
            kwargs["ContentType"] = content_type
        if content_encoding:
            kwargs["ContentEncoding"] = content_encoding

        try:
            if not args.dry_run:
                client.upload_file(
                    Bucket=bucket,
                    LocalFilePath=local_path,
                    Key=remote_key,
                    EnableMD5=False,
                    PartSize=10,
                    MAXThread=4,
                    **kwargs,
                )
            with state_lock:
                state["done"] += 1
                state["bytes"] += entry["size"]
                done = state["done"]
            tag = f" [enc={content_encoding}]" if content_encoding else ""
            print(f"[{done}/{total}] OK  {rel}{tag} ({entry['size']} bytes)")
        except (CosClientError, CosServiceError, OSError) as e:
            with errors_lock:
                errors.append((rel, str(e)))
            print(f"ERROR  {rel}  {e}", file=sys.stderr)

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        list(pool.map(upload_one, files))

    print()
    print(f"Uploaded {state['done']}/{total} files, {state['bytes']} bytes total.")
    if errors:
        print(f"FAILED: {len(errors)} files", file=sys.stderr)
        sys.exit(1)
    print("Upload complete.")


if __name__ == "__main__":
    main()
